resources:

  - name: env-params-web-staging
    type: params
    versionTemplate:
      params:
        TEMP_FF_ENABLE: true
        
  - name: intsched-vars-stage
    type: params
    version:
      params:
        ENV: nonprod
        ORG: providenceinnovation
        REPO: IntegratedScheduling

  - name: intsched-vars-stage1
    type: params
    version:
      params:
        ENV: nonprod
        ORG: providenceinnovation
        REPO: IntegratedScheduling
        
jobs:

  - name: testParams
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: env-params-web-staging
      - OUT: intsched-vars-stage
      - OUT: intsched-vars-stage1
      - TASK:
          - script: echo "$(shipctl get_resource_state intsched-vars-stage)"
          - script: >
              VERSION=5.5
          - script: shipctl put_resource_state intsched-vars-stage version $VERSION
          - script: >
              VERSION="5.6"
          - script: shipctl put_resource_state intsched-vars-stage1 version $VERSION
            
          
          
          
      
      
