resources:
        
  - name: test_secure_params
    type: params
    version:
      params:
        secure: N5MNlNxmczXVwgtXckWmvN5vdZy+lTdDKoB+SCE3EFsmXZMwzVgCuEsiwYwjqH8fNuHBnUgUnnL39CXwpaejqjWJ2iBSSVWQGCb8QqeDh4P39LpA5W98MDd75KIrimPkgOR2ZQyFjoGssQlcN+Z50aZuOLPMA1ncguFW/xs3j3DEeTFV+AwmSt3ZsjP6M11KtPKWLYIpiZSoT7rC0i5h35HBXO5JraUBWKol7oOlzIwFn7MgyZ/de0NVfeLyTw8Tndl4ZGXvzHHBZdB6iYYUDlzZPIo3lIVmF2Uyo2T8S0cSzG6zJpsGlUMEVky04/jQ5KvCMD1iggueb0zFIo6mGA==

jobs:

  - name: test_secure_params_job
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: test_secure_params
      - TASK:
          script:
            - echo $a
      
      
