resources:
        
  - name: test_secure_params
    type: params
    version:
      params:
        secure: sKhjI/hk1ZTe2hCzpvu+iXxaLCsrhiAjz+sjM9Gawr6C1ndLfVBRXqVS5FYS+BIt2cN8uIpNABDutcYGu6ioo4QgSFDQVeH02hTKiXfGUasKY8c5eFYI2/Bp0x+LEV3QBfmdUHZKrU2Wr6Skny0E+5mlHfat31hWdvfsLIs+oPxQC0IwU05rptKnTubyHoACqQlA8RZBGoUSKeatFNHUp7UDWJRYA4RN2fDtuqkX2ZCbXyqAMCaKrqbJQ0kXoz9iQpJEGCwjMmqf0XPlX2AN6VyQOIP2SP/cirSz7t259pMMUR8k6e4FtYLW8hfbX1Rco7sPSsuyUZeITjEGl4Lqfg==

jobs:

  - name: test_secure_params_job
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: test_secure_params
      - TASK:
          script:
            - echo $a
            - echo $b
            - echo $c
      
      
