resources:

  - name: env-params-web-staging
    type: params
    versionTemplate:
      params:
        TEMP_FF_ENABLE: true
        
  - name: intsched-vars-stage
    type: params
    version:
      params:
        ENV: nonprod
        ORG: providenceinnovation
        REPO: IntegratedScheduling

  - name: intsched-vars-stage1
    type: params
    version:
      params:
        ENV: nonprod
        ORG: providenceinnovation
        REPO: IntegratedScheduling
        
  - name: INTSCHEDREPO
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: ambarish2012/params-runSh-sample
      # Remove branch below if you want PRs to be triggered for all branches.
      # If you want to trigger for some branches but not others, use branches tag
      # as documented here: http://docs.shippable.com/platform/workflow/resource/gitrepo/#gitrepo
      branch: master
        
jobs:

  - name: testParams
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: env-params-web-staging
      - IN: INTSCHEDREPO
      - OUT: intsched-vars-stage
      - OUT: intsched-vars-stage1
      - TASK:
          script:
            - REPO_PATH=$INTSCHEDREPO_STATE
            - cd $REPO_PATH
            - REPO_SSH=$INTSCHEDREPO_SSH_URL
            - git remote set-url origin $REPO_SSH
            - git checkout master
            - touch test$BUILD_NUMBER.txt
            - echo hello > test$BUILD_NUMBER.txt
            - git add .
            - git commit -m '[skip ci] Release version bump'
            - git push -u origin master
            - VERSION=5.5
            - shipctl put_resource_state intsched-vars-stage version $VERSION
            - echo "$(shipctl get_resource_state intsched-vars-stage)"
            
          
          
          
      
      
