resources:

        
  - name: test_secure_params
    type: params
    version:
      params:
        secure: fh3WQRmtLUBEo3KjuntuKIFTdoE2ahkLQIe6TKWeZaKvQj/rhu6tWtVuDneZT4D7NY6BE85HzDUggrzkJwI42j85rGehIVChlUcQfQa8Myce+h4jXDKM8bZ3VolhbOIlQT1gP9Sk3h/7q4Tj/EsEmYMNPmI5CN/29GcVduuJhtvAOjxf7k0Bs3hjQRZRvjL/43iqNi79OuOHaEPhRPi5kSQjx86I4ofQesDw++8ZacfeA6XUqqQUDI75ldY0294kK/SyWGbelDGcRRKIeOrBeC+XkQ0euGaJOYcAyqeefE3epitkb5z9xVwRqwgDwydEwengF3VZejZ2hdgJYSF+YQ==
    
jobs:

  - name: test_secure_params_job
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: test_secure_params
      - TASK:
          script:
            - echo $a
      
      
