resources:
        
  - name: test_secure_params
    type: params
    version:
      params:
        secure: F+fBILLQvdOeuRYTJTe+tu4teLrdhyC4noFQPKVlOXEa7jFwWd8ie9yBtc7MdcwiyA3O30XY/dBXQCvvzQCn1il4CJITLRN3K2fDTfcW/AJfLE+pVQjmv/OVQ7cFfC4YFwfRituevse/eP8KF5fcpEtXjwkFYHMMp/mUN/pqrZ+OvzVPXve0LKE6AXaaqlqfdZ/6DU0jW7HNKcsw/LYi5+Hvk/OKVPDqD2OKhKcb9t8Z+hI1vMqzzdvbI2OymaHbo5UPHczXL0B/yCBKVvhndKSCmdEHr3vvmiPgNcq6xygmFXZ28DAqCgV2BuAAtxMruXFkK76gRTte3uizPGpX5Q==

jobs:

  - name: test_secure_params_job
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: test_secure_params
      - TASK:
          script:
            - echo $a
      
      
